from __future__ import annotations

from scoundrel_tui.assets import (
    ART_CACHE,
    ASSET_ROOT,
    BARE_HANDS_IMAGE,
    CLUBS_ASSET_FOLDER,
    MONSTER_PORTRAITS,
    PIXEL_MONSTER_PORTRAITS,
    PIXEL_POTION_IMAGES,
    PIXEL_WEAPON_IMAGES,
    POTION_ASSET_FOLDER,
    POTION_IMAGES,
    ROOT,
    SPADES_ASSET_FOLDER,
    STORY_IMAGES,
    WEAPON_ASSET_FOLDER,
    WEAPON_IMAGES,
    asset_for,
    card_asset_map,
    pixel_folder,
)
from scoundrel_tui.cards import Card, MAX_HEALTH, RANK_NAMES, SUIT_GLYPHS, SUIT_STYLE, Suit
from scoundrel_tui.game import GameState
from scoundrel_tui.images import (
    DEFAULT_IMAGE_CELL_HEIGHT_PX,
    DEFAULT_IMAGE_CELL_WIDTH_PX,
    ITEM_CARD_ART_SCALE,
    cached_terminal_image,
    card_art,
    card_image,
    card_spacer,
    enable_tmux_tgp_passthrough,
    env_int,
    fitted_image,
    image_cell_pixels,
    image_mode,
    transparent_image,
)
from scoundrel_tui.tui import ScoundrelApp, main

__all__ = [
    "ART_CACHE",
    "ASSET_ROOT",
    "BARE_HANDS_IMAGE",
    "CLUBS_ASSET_FOLDER",
    "Card",
    "DEFAULT_IMAGE_CELL_HEIGHT_PX",
    "DEFAULT_IMAGE_CELL_WIDTH_PX",
    "GameState",
    "ITEM_CARD_ART_SCALE",
    "MAX_HEALTH",
    "MONSTER_PORTRAITS",
    "PIXEL_MONSTER_PORTRAITS",
    "PIXEL_POTION_IMAGES",
    "PIXEL_WEAPON_IMAGES",
    "POTION_ASSET_FOLDER",
    "POTION_IMAGES",
    "RANK_NAMES",
    "ROOT",
    "SUIT_GLYPHS",
    "SUIT_STYLE",
    "SPADES_ASSET_FOLDER",
    "STORY_IMAGES",
    "ScoundrelApp",
    "Suit",
    "WEAPON_ASSET_FOLDER",
    "WEAPON_IMAGES",
    "asset_for",
    "cached_terminal_image",
    "card_art",
    "card_asset_map",
    "card_image",
    "card_spacer",
    "enable_tmux_tgp_passthrough",
    "env_int",
    "fitted_image",
    "image_cell_pixels",
    "image_mode",
    "main",
    "pixel_folder",
    "transparent_image",
]


if __name__ == "__main__":
    main()
